:Author: mwilly
:Email: matt.willy@gmail.com
:Date: 17/07/2018
:Revision: version#
:License: Public Domain

= Project: StopLight

Simple Example of a stoplight, switching between Green, Yellow, and Red LEDs.

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact mwilly <matt.willy@gmail.com>

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name       | Quantity
| R1 | 220Ohm Resistor | 3       
| L1 | Red LED         | 1
| L2 | Yellow LED      | 1
| L3 | Green LED       | 1
| A1 | Arduino Uno     | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
